import type { Metadata } from "next";

import Gnb from "./_components/layout/gnb";

import localFont from "next/font/local";
import "../src/css/globals.css";
import Footer from "./_components/layout/footer";
import { SessionProvider } from "next-auth/react";

const geistSans = localFont({
  src: "../src/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../src/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "부활한 구동여지도",
  description: "Generated by The Team BoEun",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable} body`}>
        <div className="root">
          <Gnb />
          <div className="content-wrap">
            {children}
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
